;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Pzt Mar 18 2019
; Processor: AT89C51
; Compiler:  ASEM-51 (Proteus)
;====================================================================

$NOMOD51
$INCLUDE (8051.MCU)

;====================================================================
; DEFINITIONS
;====================================================================
ORG 8000H
DB 1000000B
DB 1111001B
DB 0100100B
DB 0110000B
DB 0011001B
DB 0010010B
DB 0000010B
DB 1111000B
DB 0000000B
DB 0010000B
;====================================================================
; VARIABLES
;====================================================================
digit1  EQU 30H
digit2  EQU 31H
digit3  EQU 32H
digit4  EQU 33H
sec     EQU 34H
min     EQU 35H
hour    EQU 36H
display EQU P0
anode1  EQU P2.0
anode2  EQU P2.1
anode3  EQU P2.2
anode4  EQU P2.3
LED     EQU P1.0
button1 EQU P3.0
button2 EQU P3.1
button3 EQU P3.2
button4 EQU P3.3
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      org   0000h
      jmp   Start

;====================================================================
; CODE SEGMENT
;====================================================================

      org   0100h
Start:	
		CLR  button1
		CLR  button2
		CLR  button3
		CLR  button4
	    MOV  sec, #00
	    MOV  min, #00
	    MOV  hour, #12
main: 
	    MOV  A, hour
	    MOV  B, #10
	    DIV  AB
	    MOV  digit1, A
	    MOV  digit2, B
	    MOV  A, min
	    MOV  B, #10
	    DIV  AB
	    MOV  digit3, A
	    MOV  digit4, B
nextsec:
		MOV  R0, #50
L1: 
		CALL Show
		JNB  button1, M1
		INC  hour
		MOV  A, hour
		CJNE A, #24, N1
		MOV  hour, #00
N1:		CALL Delay_300ms
		JMP  main
M1:		JNB  button2, M2
		DEC  hour
		MOV  A, hour
		JMP  skip
jumpToMain:	JMP  main
skip:	CJNE A, #-1, N2
		MOV  hour, #23
N2:		CALL Delay_300ms
		JMP  main
M2:		JNB  button3, M3
		INC  min
		MOV  A, min
		CJNE A, #59, N3
		MOV  min, #00
N3:		CALL Delay_300ms
		JMP  main
M3:		JNB  button4, M4
		DEC  min
		MOV  A, min
		CJNE A, #-1, N4
		MOV  min, #59
N4:		CALL Delay_300ms
		JMP  main
M4:		DJNZ R0, L1
		INC  sec
		CPL  LED
		MOV  A, sec
		CJNE A, #60, nextsec
		MOV  sec, #0
		INC  min
		MOV  A, min
		CJNE A, #60, main
		MOV  min, #00
		INC  hour
		MOV  A, hour
		CJNE A, #24, jumpToMain
		MOV  hour, #00
		JMP  main
	 
	  
Delay_5ms:    
				MOV R5, #1
	  K2: 		MOV R6, #10
	  K1: 		MOV R7, #250
	  K0: 		DJNZ R7, K0
				DJNZ R6, K1
				DJNZ R5, K2
				RET

Delay_20ms:
			CALL Delay_5ms
			CALL Delay_5ms
			CALL Delay_5ms
			CALL Delay_5ms
			RET

Delay_100ms:
			CALL Delay_20ms
			CALL Delay_20ms
			CALL Delay_20ms
			CALL Delay_20ms
			CALL Delay_20ms
			RET
			
Delay_300ms:
			CALL Delay_100ms
			CALL Delay_100ms
			CALL Delay_100ms
			RET
	  
Show:	SETB anode1
		CLR  anode2
		CLR  anode3
		CLR  anode4
		MOV  DPTR, #8000H
		MOV  A, digit1
		MOVC A, @A + DPTR
		MOV  display, A
		CALL Delay_5ms
		CLR  anode1
		SETB anode2
		MOV  A, digit2
		MOVC A, @A + DPTR
		MOV  display, A
		CALL Delay_5ms
		CLR  anode2
		SETB anode3
		MOV  A, digit3
		MOVC A, @A + DPTR
		MOV  display, A
		CALL Delay_5ms
		CLR  anode3
		SETB anode4
		MOV  A, digit4
		MOVC A, @A + DPTR
		MOV  display, A
		CALL Delay_5ms
		CLR  anode1
		CLR  anode2
		CLR  anode3
		CLR  anode4
		RET
		
Loop:	
      jmp Loop

;====================================================================
      END
