;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Pzt Mar 18 2019
; Processor: AT89C51
; Compiler:  ASEM-51 (Proteus)
;====================================================================

$NOMOD51
$INCLUDE (8051.MCU)

;====================================================================
; DEFINITIONS
;====================================================================
ORG 800H
DB 0
DB 1
DB 3
DB 6
DB 10
DB 15
DB 20
DB 27
DB 35
DB 43
DB 53
DB 64
DB 75
DB 88
DB 102
DB 116
DB 132
DB 149
DB 166
DB 185
DB 205

ORG 830H
DB 0
DB 6
DB 6
DB 4
DB 2
DB 0
DB 7
DB 5
DB 2
DB 9
DB 5
DB 2
DB 9
DB 5
DB 2
DB 8
DB 5
DB 1
DB 7
DB 4
DB 0

ORG 900H
;====================================================================
; VARIABLES
;====================================================================
x EQU 30H
counter EQU 31H
timer EQU 32H
dot EQU P1.7
display2 EQU P2
display4 EQU P3
anode2_1 EQU P1.1
anode2_2 EQU P1.0
anode4_3 EQU P1.5
anode4_2 EQU P1.4
anode4_1 EQU P1.3
anode4_4 EQU P1.2
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      org   0000h
      jmp   Start
	  
	  org	000bh
	  jmp	show_display_2
	  
	  org   001bh
	  jmp	show_display_4
	  
;====================================================================
; CODE SEGMENT
;====================================================================
org   0900h
Start:				
					MOV TMOD, #11H
					MOV IE, #8AH
					MOV TL0, #55H
					MOV TH0, #55H
					MOV TL1, #55H
					MOV TH1, #55H
					SETB TR0
					SETB TR1
					SETB dot
					SETB P1.0
					SETB P1.1
					SETB P1.2
					SETB P1.3
					SETB P1.4
					SETB P1.5
					MOV counter, #0
					MOV timer, #0
		
Loop:	
      jmp Loop	

show_display_2:	CLR TR0
				SETB anode2_1
				CLR anode2_2
				MOV A, counter
				MOV B, #10
				DIV AB
				MOV display2, A
				CALL Delay_1ms
				CLR anode2_1
				SETB anode2_2
				MOV display2, B
				CALL Delay_1ms
				CLR anode2_1
				CLR anode2_2
				INC timer
				MOV A, timer
				CJNE A, #18, x1
				MOV timer, #0
				MOV A, counter
				INC counter
				MOV A, counter
				CJNE A, #21, x1
				MOV counter, #0
x1:				MOV TL0, #55H
				MOV TH0, #55H
				SETB TR0
				RETI
				
				
show_display_4:	CLR TR1
				SETB dot
				SETB anode4_1
				CLR anode4_2
				CLR anode4_3
				CLR anode4_4
				MOV DPTR, #800H
				MOV A, counter
				MOVC A, @A + DPTR
				MOV B, #10
				DIV AB
				CLR dot
				MOV display4, B
				CALL Delay_1ms
				MOV B, #10
				CLR anode4_1
				SETB anode4_2
				DIV AB
				SETB dot
				MOV display4, B
				CALL Delay_1ms
				MOV B, #10
				CLR anode4_2
				SETB anode4_3
				MOV display4, A
				CALL Delay_1ms
				CLR anode4_3
				SETB anode4_4
				MOV DPTR, #830H
				MOV A, counter
				MOVC A, @A + DPTR
				MOV display4, A
				CALL Delay_1ms
				CLR anode4_1
				CLR anode4_2
				CLR anode4_3
				CLR anode4_4
				MOV TL1, #55H
				MOV TH1, #55H
				SETB TR1
				RETI
	
Delay_1ms:
				MOV R5, #1
	  M2: 		MOV R6, #2
	  M1: 		MOV R7, #250
	  M0: 		DJNZ R7, M0
				DJNZ R6, M1
				DJNZ R5, M2
				RET
				
;====================================================================
      END
